# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c73b22d69b5c1bfacc31ace744b96057e8051af2b535408e65993c13dc1104683f6274a624ff05a0defbe6d6c2b2fb3dc2682720d711509a6604811b6d3738d

test:
  secret_key_base: 3b57ab6c29113ffaf93dd9a204879e9266ce35a3b8c3d500b68a0f9916f57214b0438d3c100655c04264acf4d83c3aa715a40ac587a70d59f69ac096334e5f09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
